/**
 * Dump the TypeScript shape generators' exact output as Rust test fixtures.
 *
 * The Rust ports in `mocanvas-geo::shapes` must reproduce these word for word,
 * so this writes down what the TS implementation actually produces (rounded to
 * f32, which is what the engine's wire format stores) rather than numbers
 * anybody typed by hand.
 *
 * Run from the repo root:
 *   node node_modules/.pnpm/vite-node@*\/node_modules/vite-node/vite-node.mjs \
 *     apps/bench/scripts/dump-shape-fixtures.mts
 */
import { writeFileSync } from "node:fs"
import { GEO_SHAPE_KINDS } from "@mocanvas/editor"
import { getGeoGeometry } from "../../../packages/mocanvas/src/shapes/geo-helpers"
import { catmullRomToBezier } from "../../../packages/mocanvas/src/shapes/spline-helpers"
import { smoothPoints } from "../../../packages/mocanvas/src/shapes/draw-helpers"

const f32 = new Float32Array(1)
const u32 = new Uint32Array(f32.buffer)
/**
 * The f32 bit pattern the wire format would carry for `v`, as 8 hex digits.
 *
 * The fixture stores bits rather than decimal so that Rust reads back exactly
 * the float JavaScript produced, with no round-tripping through a printer and
 * a parser that might disagree in the last place.
 */
function bits(v: number): string {
  f32[0] = v
  return u32[0]!.toString(16).padStart(8, "0")
}

/** Boxes chosen to exercise the `min(w/3, h)` style clamps in both directions. */
const BOXES: [number, number][] = [
  [100, 100],
  [200, 60],
  [60, 200],
  [37.5, 91.25],
  [1, 1],
]

/**
 * Stroke widths the geo paths are captured at.
 *
 * Only the marks drawn inside an outline move with it — the X of an x-box is
 * pulled back by half a width at each end so its round cap lands on the corner
 * — so this is what pins that pull-back to the engine's copy of it. `10` is the
 * `xl` stroke, and on the 1x1 box it is far larger than the shape, which is
 * where the clamp on the pull-back has to hold.
 */
const STROKE_WIDTHS = [0, 3.5, 10]

const FLIPS: [boolean, boolean][] = [
  [false, false],
  [true, false],
  [false, true],
  [true, true],
]

const lines: string[] = [
  "# Generated by apps/bench/scripts/dump-shape-fixtures.mts — do not edit by hand.",
  "# Every value after the record's integer fields is an f32 bit pattern in hex.",
  "# geo    <kindIndex> <flipX> <flipY> <w> <h> <strokeWidth> <nWords> <pathWord>*",
  "# spline <closed> <nPoints> <x y>* <nWords> <p0x p0y c1x c1y c2x c2y p1x p1y>*",
  "# smooth <nPoints> <x y>* <nOut> <x y>*",
  `# kinds ${GEO_SHAPE_KINDS.join(" ")}`,
]

for (const [kindIndex, kind] of GEO_SHAPE_KINDS.entries()) {
  for (const [w, h] of BOXES) {
    for (const [flipX, flipY] of FLIPS) {
      // Only one box needs every flip; on the others the flips would just repeat
      // the same mirroring over a different rectangle.
      if ((flipX || flipY) && (w !== 100 || h !== 100)) continue
      for (const strokeWidth of STROKE_WIDTHS) {
        const words: number[] = getGeoGeometry(kind, w, h, false, { flipX, flipY }, strokeWidth).toPathWords()
        lines.push(
          [
            "geo",
            kindIndex,
            flipX ? 1 : 0,
            flipY ? 1 : 0,
            bits(w),
            bits(h),
            bits(strokeWidth),
            words.length,
            ...words.map(bits),
          ].join(" "),
        )
      }
    }
  }
}

/** Points with an uneven spacing, so a wrong Catmull-Rom tension shows up. */
const SPLINE_POINTS = [
  { x: 0, y: 0 },
  { x: 40, y: 90 },
  { x: 120, y: 10 },
  { x: 200, y: 140 },
  { x: 260, y: 30 },
]

for (const closed of [false, true]) {
  const segs = catmullRomToBezier(SPLINE_POINTS, closed)
  const words = segs.flatMap((s) => [s.p0, s.c1, s.c2, s.p1].flatMap((p) => [bits(p.x), bits(p.y)]))
  lines.push(
    [
      "spline",
      closed ? 1 : 0,
      SPLINE_POINTS.length,
      ...SPLINE_POINTS.flatMap((p) => [bits(p.x), bits(p.y)]),
      words.length,
      ...words,
    ].join(" "),
  )
}

/** A freehand run long enough to smooth, and one too short for it. */
const DRAW_RUNS: { x: number; y: number }[][] = [
  [
    { x: 0, y: 0 },
    { x: 10, y: 4 },
    { x: 22, y: 1 },
    { x: 33, y: 12 },
    { x: 41, y: 30 },
    { x: 52, y: 25 },
  ],
  [
    { x: 5, y: 5 },
    { x: 9, y: 9 },
  ],
]

for (const points of DRAW_RUNS) {
  const smoothed = smoothPoints(points)
  lines.push(
    [
      "smooth",
      points.length,
      ...points.flatMap((p) => [bits(p.x), bits(p.y)]),
      smoothed.length,
      ...smoothed.flatMap((p) => [bits(p.x), bits(p.y)]),
    ].join(" "),
  )
}

const path = new URL("../../../crates/mocanvas-geo/tests/fixtures/ts-shapes.txt", import.meta.url)
writeFileSync(path, `${lines.join("\n")}\n`)
console.log(`wrote ${lines.length} lines to ${path.pathname}`)
