/**
 * Tidy up the wasm-pack output so it can be published as part of this package.
 *
 * wasm-pack writes a `.gitignore` containing `*` and a stand-alone
 * `package.json` into its out dir. npm applies a directory's `.gitignore` even
 * to files the `files` allow-list names, so leaving it there ships an empty
 * `pkg/`; the nested `package.json` would make `pkg/` look like a separate
 * package to bundlers. Neither is wanted — `pkg/` is plain data here.
 */
import { rmSync, existsSync, readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), "..", "pkg")

for (const name of [".gitignore", "package.json", "README.md"]) {
  rmSync(join(pkgDir, name), { force: true })
}

for (const required of ["mocanvas.js", "mocanvas.d.ts", "mocanvas_bg.wasm"]) {
  if (!existsSync(join(pkgDir, required))) {
    console.error(`packages/wasm: pkg/${required} is missing — run \`pnpm --filter @mocanvas/wasm build\`.`)
    process.exit(1)
  }
}

/**
 * Emit the module `loadEngine` falls back to when the `.wasm` URL does not
 * answer with WebAssembly — a bundler that rewrote `import.meta.url` without
 * moving the asset, most often Vite's dependency optimizer. It is imported
 * dynamically, so it lands in its own chunk and is only downloaded when that
 * happens. Generated, never committed; `pkg/` is in `.gitignore` and shipped
 * through the package's `files` list.
 */
const wasm = readFileSync(join(pkgDir, "mocanvas_bg.wasm"))
writeFileSync(
  join(pkgDir, "mocanvas-wasm-base64.js"),
  `// @generated by packages/wasm/scripts/prepare-pkg.mjs from mocanvas_bg.wasm — do not edit.\nexport const wasmBase64 =\n  "${wasm.toString("base64")}"\n`,
)
writeFileSync(
  join(pkgDir, "mocanvas-wasm-base64.d.ts"),
  `// @generated by packages/wasm/scripts/prepare-pkg.mjs — do not edit.\nexport declare const wasmBase64: string\n`,
)
